[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
# (Optional) Text in landing page button
LANDING_BUTTON = "Home Page"
# (Optional) Site description on landing page
LANDING_DESCRIPTION = "A personal website I've been meaning to write since I was a kid"
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "home"
# (Optional) Site title on landing page
LANDING_TITLE = "Welcome to my personal space!"
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://github.com/NikPrav/PersonalWebsitev1"
# (Optional) Site title in navbar
SITE_TITLE = "Nikhil's Journey through the vast space of academia"
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = "bren"
# (REQUIRED) Netlify site URL
SITE_URL = "https://dynamic-swan-db57f7.netlify.app/"
# (Optional) Site Timezone
TIMEZONE = "US/New_York"
ZOLA_VERSION = "0.15.2"
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "title"
# (Optional) Google Analytics Measurement ID
GANALYTICS = ""
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = "y"
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = ""
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = ""
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = "y"
# (Optional, default blank) Additional footer content.
FOOTER = ""
# (Optional, default main) Root section name.
ROOT_SECTION_NAME = "Home"
# (Optional) visjs graph options. Can remove if desired.
GRAPH_OPTIONS = """"""